name: guzellik_merkezi
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0   # firebase_core'u 3.13.0 sürümüne güncelliyoruz
  firebase_auth: ^5.5.1
  google_maps_flutter: ^2.5.0  
  geolocator: ^10.0.0  
  cloud_firestore: ^5.6.6  # cloud_firestore'u 5.6.6 sürümüne güncelliyoruz



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/background.png
    - assets/cilt_bakimi.png
    - assets/estetik.png
    - assets/kuafor.png
    - assets/lazer.png
    - assets/mezoterapi.png
    - assets/tirnak.png